### ISSUE TITLE
pry in call method in controller.

### ISSUE THREAD

**Issue by barstuk** [lotus/lotus#205]
I have a small issue when using binding.pry in call method of controller.
When I try to use it in:
def call(params)
  binding.pry
end
It returns me error:
when_started hook failed: TypeError: bind argument must be an instance of Object
/home/adam/.rvm/gems/ruby-2.2.0/gems/pry-0.10.1/lib/pry/helpers/base_helpers.rb:22:in `bind'
(see _pry_.hooks.errors to debug)

It works only when I use:
def self.call(params)
  binding.pry
end

But I don't want to work on self for obvious reasons.

**Comment by jodosha** [comment]
@barstuk I suspect this error is caused by `shotgun`. Can you please start the server with the `--code-reloading=false` argument and check if the problem is still there?

Can you please also verify if `byebug` works fine **with** code reloading? It's my fav option and always worked. Thank you :+1:

**Comment by barstuk** [comment]
--code-reloading=false doesn't help.
byebug works all the time in every method, there's a bug with pry only.

**Comment by jodosha** [comment]
@barstuk If you want still have pry, I suggest `pry-byebug`, which combines the power of both the gems.

**Comment by barstuk** [comment]
Ekhm, I'm using pry-byebug but it's not working. : /

**Comment by xuwupeng2000** [comment]
We have the same problem. Pry does not work with Lotus.

**Comment by tomkadwill** [comment]
I've had a quick look at this. For me, pry does pause execution (as expected) but it does not show a REPL in the terminal as I would expect.

@jodosha do you know anything about this? otherwise I'll investigate.

**Comment by tak1n** [comment]
Got the same issue like @tomkadwill stated above, the execution is stopped but the pry repl not shown.

**Comment by AlfonsoUceda** [comment]
reopened issue, it seems several of us have the same problem.

we have to investigate why because pry byebug is really helpful.

@tak1n @tomkadwill have you investigated what the problem is?

**Comment by BradWheel** [comment]
@AlfonsoUceda I just encountered the same issue with pry. I can attach pry to basically any other object and get the repl as expected (e.g Object.new, STDOUT, etc), but as @tomkadwill noted, when used regularly (binding.pry), pry does pause, but I'm not able to access the repl. 

I'm just getting started with Lotus, so I haven't had too much time to poke around the source, but I think its possible the _rescue block in call (Lotus::Action) is causing some Pry confusion. After removing the Lotus::Action module, pry works correctly. 

I'll dig deeper, but wanted to throw this out there in case you had any suggestions based on the info.

**Comment by AlfonsoUceda** [comment]
@BradWheel this? https://github.com/lotus/controller/blob/master/lib/lotus/action/callable.rb#L68-L74

maybe you can check https://github.com/lotus/controller/blob/61e2347ca7357ce877b216efca6f4157ebfbe73d/lib/lotus/action/throwable.rb#L128 and play removing catch block only for testing with pry and we can find the culprit

**Comment by BradWheel** [comment]
@AlfonsoUceda I tried removing the catch block and had the same issues as before. I dug around a bit more and started to eliminate the modules included into the Action module one by one and found that if you remove both Callbacks and Callable modules, pry works as its supposed to.

**Comment by BradWheel** [comment]
@AlfonsoUceda I've narrowed down the problem to this line in pry:
https://github.com/pry/pry/blob/master/lib/pry/repl.rb#L50

The default :before_session hook is not running correctly in Lotus controller. If you remove it by adding 
`Pry.hooks.delete_hook(:before_session, :default)` when the application loads, pry works correctly.

**Comment by jodosha** [comment]
@bradwheel Thanks for your investigation. The culprit is the combination of `prepend InstanceMethods` in `Lotus::Action::Callbacks` and the to `super` in `#call`. See https://github.com/lotus/controller/blob/master/lib/lotus/action/callbacks.rb#L195

If I change `prepend` into `include`, PRY works fine w/ your test application, but it breaks Lotus::Controller.

The same thing happens for all the views, but not for entities, because `Lotus::View` uses `prepend`, but not `Lotus::Entity`.

**Comment by jodosha** [comment]
I've opened an issue on Pry project, let check what do they think :smile: https://github.com/pry/pry/issues/1471

**Comment by jodosha** [comment]
This appears to be a Pry issue, which is now fixed in master. Please reference the issue above. :smile:

**Comment by jodosha** [comment]
Folks, Mr @banister released a new version of Pry (0.10.2) with the purpose of not get all of you stuck with this problem. How awesome is he? :100: :sparkles: 

Please let us to know if something isn't working correctly for you.

**Comment by josemota** [comment]
Arigato gozaimasu, @banister!

**Comment by nozpheratu** [comment]
I'm still getting this issue even with Pry v0.10.2. @bradwheel's temporary fix works for me.

**Comment by manuwell** [comment]
Its weird, because if you call `binding.pry` from another method in the controller it works, if `binding.pry` is called directly from `call#method` it doesn't.  

```ruby
def call(params)
  mycall(params)
end

def mycall(params)
  binding.pry # works
end 
```

**Comment by sdorunga1** [comment]
Still happening, would be nice to get a fix for this.

**Comment by jodosha** [comment]
This is a gentle reminder that probably you should ping PRY maintainers here. https://github.com/pry/pry/issues/1471

**Comment by banister** [comment]
Can you guys check whether things work with the pre release pry gem (cut a few days ago)? Cc @jazzonmymind

**Comment by jazzonmymind** [comment]
i think it is probably still an issue. @banister pushed a potential fix in 0.10.2 but i don't think it covered every scenario. please try 0.11.0.pre, just in case.

**Comment by jdickey** [comment]
I'm having the same problem with Hanami 1.0.0 and Pry 0.11.0pre2. Not only does the terminal hang after Pry shows the source listing but before it starts the REPL, but my terminal is left in "raw" mode (`stty sane` to the rescue) _and_ the Ruby process is still running even after Control-C gets me back to the terminal; `ruby` has to be explicitly killed to avoid sucking 98%+ of a CPU.

I see we're coming up on the two-year anniversary of pry/pry#1471 (which is re-asked as pry/pry#1621?). Is there some useful information someone out there knows that I'm missing?

----

```
// #rant-mode: on # issue report complete; what follows is a question for the Omniverse
```

After coming back to Ruby 7 years ago, I'm just about ready to go elsewhere. JavaScript fatigue may be real, and the Elixir community and ecosystem may be small compared to the Ruby analogues, *but* having promising new(ish) frameworks'/etc's issues stalled two years due to a single-point-critical tool (with show-stopper for us) bugs that hasn't seen a real release in over a year is *troubling.* I *love* the Ruby language, especially now that our shop is Rails-free for production code, but this is the sort of thing that makes us ask "do we want to go back and hit ourselves over the head with Rails, or do we want to go play dependency Whac-A-Mole with Node, or explore the new frontier of Elixir…or do we just tie the end of the rope around our wrists and hang in there until the pipeline in Rubyland gets unplugged?

How do you folks *cope?* Seriously? Or am I just being bass-ackwards about this because it's 3 AM and I've put in 16 hours today?

```
// #rant-mode: off
```

**Comment by jdickey** [comment]
Ping? Does anybody have any news here or in relation to pry/pry#1621? Or is everybody else as buried as I am by their day jobs? I'm a week away from making a decision on whether to use Hanami for an upcoming revenue project; if we don't have a viable debug strategy, Hanami is going to be a much harder sell than I'd like it to be. Anything?

**Comment by cllns** [comment]
@jdickey Do you need to use `pry`, or can you use other "viable debug strategies"? If a non-`pry` solution is possible, I'd recommend exploring that. 
(I've heard great things about `pry`, but I don't use it, personally)

**Comment by banister** [comment]
@jdickey i don't use hanami, if you can provide a super simple minimal reproduction i might be able to  look into it...

**Comment by cllns** [comment]
@banister thank you!! I created an example on a branch of our simple "Getting Started" project (called bookshelf). 

I was able to reproduce it too. `binding.pry` stops code execution, but doesn't show anything. Ctrl-C exits out of `hanami server`, but the ruby process still runs in the background, at full throttle. I had to do the `ps aux | grep ruby` and `kill *PID*` to fix it.

The branch is `pry-bug-example`, available here: https://github.com/hanami/bookshelf/tree/pry-bug-example

**Comment by Fedcomp** [comment]
Hello guys, can we make some workaround in hanami itself?

**Comment by banister** [comment]
can you guys confirm whether the most recent pry version fixes these issues?

**Comment by Fedcomp** [comment]
@banister i can see action witht the msot recent pry version.

**Comment by jodosha** [comment]
@banister thank you very much! 💯
